# -*- coding: utf-8 -*-
"""ImersaoDados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TQVzgUkwDH8A-qrQ3J-OjTWu-NJDyFus

### Desafio 01: Investigar por que a classe tratamento é tão desbalanceada?

### Desafio 02: Plotar as cinco últimas linhas da tabela

### Desafio 03: Proporção das classes tratamento?

### Desafio 04: Quantos tipos de drogas foram investigados?

### Desafio 05: Procurar na documentação o método query (pandas).

### Desafio 06: Renomear as colunas tirando o hífen.

### Desafio 07: Colocar título dos gráficos, deixar bonitos (Matplotlib.pyplot)

### Desafio 08: Resumo do que aprendeu
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
url_dados = 'https://github.com/alura-cursos/imersaodados3/blob/main/dados/dados_experimentos.zip?raw=true'
dados = pd.read_csv(url_dados, compression = 'zip')
dados

dados.head()

dados.shape

dados['tratamento']

dados['tratamento'].unique()

dados['tempo'].unique()

dados['dose'].unique()

dados['droga'].unique()

dados['g-0'].unique()

dados['dose'].value_counts()

dados['tratamento'].value_counts()

dados['tratamento'].value_counts(normalize= True)

dados['dose'].value_counts(normalize= True)

dados['tratamento'].value_counts().plot.pie()

dados['tempo'].value_counts().plot.pie()

dados['tempo'].value_counts().plot.bar()

"""Mostrar dados que g-0 são maiores que zero"""

dados['g-0']>0

dados_filtrados = [dados['g-0']>0]

### RESPOSTA Desafio 1 Investigar por que a classe tratamento é tão desbalanceada?
dados['tratamento'].value_counts()

### RESPOSTA Desafio 2 Plotar as cinco últimas linhas da tabela
dados.tail()

dados['tratamento'].value_counts(normalize = True)

dados['dose'].value_counts(normalize = True)

dados['droga'].value_counts(normalize = True)

### RESPOSTA Desafio  3 Proporção das classes tratamento?

dados['tratamento'].value_counts(normalize=True)

### RESPOSTA Desafio 4 Quantos tipos de drogas foram investigados?
dados['droga'].value_counts()
#Existem 3289 tipos de drogas, sendo os seguintes mais ocorrentes:

### RESPOTAS Desafio  5 Procurar na documentação o método query (pandas).
dados_filtrados = dados[dados['g0']>0]
dados_filtrados

### RESPOSTA Desafio 6 Renomear as colunas tirando hífen
dados.columns = dados. columns.str.replace('-','')

### RESPOSTA Desafio 7 Colocar título dos gráficos, deixar bonitos

dados_tempo = dados['tempo'].value_counts().plot.bar()
dados_tempo.set_xlabel('Tempo(horas)')
dados_tempo.set_ylabel('Nº de testes')
dados_tempo.set_title('Tabela de testes')

### RESPOSTA Desafio 8 - Resumo do aprendizado

Aprendi a comprimir arquivo zipado com o Python Pandas
Criar gráficos e formata-los
Analisar aspectos individuais